### ISSUE TITLE
armor_detector/model下面哪个模型最优呢？

### ISSUE THREAD

**Issue by YKJamesMoriarty** [ev3rm0re/cque_rm_vision_src#1]
大佬你好，我想请问下model里面有3.19的yolov8_e50，有7.19的yolov8n_e50，这两个时间段训练的模型有哪些不同呢，你尝试以后性能两者怎么样鸭，目前还存在什么问题呢？我可以添加您的联系方式和您进一步交流嘛，我最近也在负责RM自瞄的改进～

**Comment by ev3rm0re** [comment]
3.19是用官方数据集训练的，这个效果更好
7.19是自己做的数据集训练的

**Comment by YKJamesMoriarty** [comment]
噢噢，就是说3.19是RM官方提供的装甲板标注好的数据集是吧！那前辈，您可以试试把官方数据集和您自己做的数据集合成一个更大的数据集进行训练，这样可能效果会更不错呢！～

**Comment by YKJamesMoriarty** [comment]
> 3.19是用官方数据集训练的，这个效果更好 7.19是自己做的数据集训练的

噢噢，就是说3.19是RM官方提供的装甲板标注好的数据集是吧！那前辈，您可以试试把官方数据集和您自己做的数据集合成一个更大的数据集进行训练，这样可能效果会更不错呢！～

**Comment by YKJamesMoriarty** [comment]
have figured out
